### DATA ANALYTICS AND ANACONDA SET UP (DAY 1)

### PYTHON FUNDAMENTAL (DAY 2)

In [12]:
# Introduction Script in Python
# Defining variables
name = "Chika Chukwu"
age = 25
height = 5.4
is_a_dataanalyst = True
hobbies = ["reading", "watching movies", "games"]
address = {
    "street": "11 Dracula Street",
    "city": "Ikeja",
    "state": "Lagos",
}
languages_spoken = ("English","Igbo")  

In [13]:
# Printing introduction with variables
print("Hello! My name is", name)
print("I am", age, "years old and", height, "feet tall.")
if is_a_dataanalyst:
    print("I am a Data Analyst.")
else:
    print("I am not a Data Analysts")
print("My hobbies are:", hobbies)
print("You can find me at:", address["street"], ",", address["city"], ",", address["state"])
print("I speak the following languages",languages_spoken)

Hello! My name is Chika Chukwu
I am 25 years old and 5.4 feet tall.
I am a Data Analyst.
My hobbies are: ['reading', 'watching movies', 'games']
You can find me at: 11 Dracula Street , Ikeja , Lagos
I speak the following languages ('English', 'Igbo')


### DATA TYPES (DAY 3)

In [ ]:
#Expressions in Python 

In [12]:
# Define variables with different data types
integer_var = 42  # Integer data type
float_var = 3.14  # Float data type
string_var = "Hello Beautiful,"  # String data type
bool_var = True  # Boolean data type
list_var = [1, 2, 3, 4, 5]  # List data type
tuple_var = (1, 2, 3)  # Tuple data type
dictionary_var = {"name": "Chika", "age": "25",}  # Dictionary data type

In [13]:
# Expressions using different data types
addition = integer_var + float_var  # Adding an integer and a float-(Arithmetic Expression)
concatenation = string_var + " You Look Amazing!!!"  # Concatenating two strings-(Arithmetic Expression) 
logical = bool_var and False  # Performing logical AND operation-(Logical Expression)
list_indexing = list_var[2]  # Accessing element at index 2 in the list-(Indexing Expression)
tuple_unpacking = tuple_var[0]  # Unpacking first element from the tuple-(Indexing Expression)
dictionary_access = dictionary_var["name"] # Accessing value by key "name" from dictionary-(Dictionary Access Expression)

In [14]:
# Print the results
print("Addition:", addition)
print("Concatenation:", concatenation)
print("Logical:", logical)
print("List Indexing:", list_indexing)
print("Tuple Unpacking:", tuple_unpacking)
print("Dictionary Access:", dictionary_access)

Addition: 45.14
Concatenation: Hello Beautiful, You Look Amazing!!!
Logical: False
List Indexing: 3
Tuple Unpacking: 1
Dictionary Access: Chika


### STRING OPERATIONS AND METHOD (DAY 4)

In [2]:
# ### Basic String Operations
# Concatenation
hello = "Hello"
beautiful = "Beautiful"
people = "People"
hello_people = hello + " " + beautiful + " " + people
print(hello_people)

Hello Beautiful People


In [3]:
# Repetition
laugh = "Ha" * 3
print(laugh)

HaHaHa


In [4]:
# Slicing
first_four = hello[0:4]
print(first_four)

Hell


In [10]:
# Length
length = len(hello_people)
print(length)

22


In [49]:
### Common String Methods
s = "Hello, Beautiful!"
print(s)

Hello, Beautiful!


In [50]:
# Capitalize
capitalized = s.capitalize()
print(capitalized)

Hello, beautiful!


In [51]:
# Upper and lower case
upper_case = s.upper()
lower_case = s.lower()
print(upper_case)
print(lower_case)

HELLO, BEAUTIFUL!
hello, beautiful!


In [52]:
# Find
position = s.find("Beautiful")
print(position)

7


In [53]:
# Replace
new_string = s.replace("Python", "World")
print(new_string)

Hello, Beautiful!


### DATA STRUCTURES (LIST, TUPLES, DICTIONARY, SET) (DAY 5)

In [1]:
# List
# Storing a list of daily sales figures for a store.
daily_sales = [1000, 1200, 1300, 1100, 1500, 1400, 1600]
print(daily_sales)

[1000, 1200, 1300, 1100, 1500, 1400, 1600]


In [2]:
# Tuples
# Storing coordinates of data points in a 2D space.
data_points = ((1, 2), (3, 4), (5, 6), (7, 8))
print(data_points)

((1, 2), (3, 4), (5, 6), (7, 8))


In [10]:
# Dictionaries
# Storing information about customers in a database.
customer = {
    'name': 'Alice',
    'age': 30,
    'gender': 'female',
    'city': 'New York'
}
print(customer)

{'name': 'Alice', 'age': 30, 'gender': 'female', 'city': 'New York'}


In [5]:
# Sets
# Storing unique values of different product categories.
product_category = {'Clothing', 'Electronics', 'Cosmetics', 'Skincare', 'Jewelries','Electronics','Clothing'}
print(product_category)

{'Jewelries', 'Clothing', 'Skincare', 'Cosmetics', 'Electronics'}


### OPERATORS AND CONTROL STRUCTURES: LOOPS AND DECISIONS (DAY 6)

In [ ]:
## Control Structures in Python

Control structures in Python are used to control the flow of execution of the program. This includes conditional statements and loops.

### If Statement
The `if` statement is used for conditional execution.


x = 10
if x > 5:
    print("x is greater than 5")


### While Loop
The `while` loop in Python is used for repeated execution as long as an expression is true.


count = 0
while count < 5:
    print(count)
    count += 1


### For Loop
The `for` loop in Python is used for iterating over a sequence (list, tuple, string, etc.)


for i in range(5):
    print(i)



#### Problem: Determining the Eligibility for a Scholarship Based on Grades
Description:
A university wants to determine which students are eligible for a scholarship based on their grades. 
The scholarship criteria state that a student must have an average grade of 85 or above and no grade below 70. 
We will write a Python program to check a list of students' grades and determine their eligibility.

Solution:
We'll use a dictionary to store students' names as keys and their list of grades as values. 
Then, we'll use loops and if-else statements to calculate each student's average grade and check if they meet the criteria for the scholarship


In [5]:
# Dictionary of students' names and their list of grades
students_grades = {
    "Alice": [88, 92, 85, 78, 90],
    "Bob": [75, 80, 79, 82, 84],
    "Charlie": [90, 85, 87, 93, 89],
    "David": [65, 70, 72, 68, 74],
    "Eve": [88, 91, 85, 87, 90]
}

# Scholarship criteria
min_average = 85
min_grade = 70

# Check each student's eligibility
for student, grades in students_grades.items():
    # Calculate average grade
    average_grade = sum(grades) / len(grades)
    
    # Check if the student meets the criteria
    if average_grade >= min_average and all(grade >= min_grade for grade in grades):
        print(f"{student} is eligible for the scholarship with an average grade of {average_grade:.2f}.")
    else:
        print(f"{student} is not eligible for the scholarship. Average grade: {average_grade:.2f}.")


Alice is eligible for the scholarship with an average grade of 86.60.
Bob is not eligible for the scholarship. Average grade: 80.00.
Charlie is eligible for the scholarship with an average grade of 88.80.
David is not eligible for the scholarship. Average grade: 69.80.
Eve is eligible for the scholarship with an average grade of 88.20.


## Error Processing, Exception Raising and Handling ( DAY 7) 

#### Looking at Specific Examples of these Types of Errors:

In [1]:
# Syntax error

print("Hello"  # Missing closing parenthesis
 

SyntaxError: incomplete input (4013463004.py, line 4)

In [2]:
# Type error

num = 5
print("Number: " + num)  # Trying to concatenate a string with an integer

TypeError: can only concatenate str (not "int") to str

In [3]:

# Name Error

print(x)  # Variable x is not defined

NameError: name 'x' is not defined

In [4]:
# Value Error
int("abc")  # Converting a string that cannot be converted to an integer

ValueError: invalid literal for int() with base 10: 'abc'

In [5]:
# Index Error 
my_list = [1, 2, 3]
print(my_list[3])  # Accessing an index that is out of range

IndexError: list index out of range

In [6]:
# Zero Division Error
result = 10 / 0  # Dividing by zero

ZeroDivisionError: division by zero

### Error Handling in Practice

The *`try...except`* block is used to handle exceptions in Python. Here's the syntax of try...except block:




In [ ]:
try:
    # code that may cause exception
    
except:  
    # code to run when exception occurs

In [10]:
# Intentionally introducing an error by trying to perform an operation that does not apply to the file's content
try:
    # Open a file (intentionally non-existent for this example)
    with open("non_existent_file.txt", "r") as file:
        # Attempt to read the content of the file
        content = file.read()
        
        # perform an operation that does not apply to the file's content
        # In this case, we're trying to split the content by a comma, assuming it's CSV data
        # However, since the file doesn't exist, the content will be an empty string, and splitting it will raise an error
        data = content.split(',')
        
        # Print the data
        print(data)

# Handle the FileNotFoundError exception
except FileNotFoundError:
    # If the file is not found, print an error message
    print("File not found. Please make sure the file exists.")

# Handle any other exceptions
except Exception as e:
    # If any other error occurs, print the error message
    print("An error occurred:", e)


File not found. Please make sure the file exists.


### FUNCTIONS AND MODULES ( DAY 8) 

In [10]:
#DEFINING FUNCTION

def greet(name):
    # Concatenating "Hello, " with the provided name parameter
    return "Hello, " + name

# Calling the greet function with the argument "Alice" and printing the result
print(greet("Alice"))

Hello, Alice


In [23]:
def uppercase(name):
    # Concatenating "Hello, " with the provided name parameter
    return "Congratulations!!! " + name
    
   # Calling the uppercase function with the argument and printing the result 
print(uppercase("Chika" + " " + "Chukwu"))

Congratulations!!! Chika Chukwu


In [36]:
def add_flavor(name):
    # Concatenating the provided name with a list of ice cream flavors
    flavors = ['Chocolate', 'Cookies and Cream','and Peanut butter']
    return name + ', '.join(flavors)

# Calling the add_flavor function with the argument and printing the result 
print(add_flavor("Chika"+ " " + "favorite ice cream Flavors" + " " + "are,"+ " "))


Chika favorite ice cream Flavors are, Chocolate, Cookies and Cream, and Peanut butter


### FILE HANDLING AND DATA INPUT/OUTPUT ( DAY 9)

In [19]:

# Import python libraries
import pandas as pd
import numpy as np

# Function to read data from a CSV file
def read_csv(file_path):
    try:
        df = pd.read_csv(file_path)
        print("File read successfully.")
        return df
    except FileNotFoundError:
        print(f"Error: The file at {file_path} was not found.")
        return None
   

# Function to perform basic statistical analysis
def analyze_data(df):
    if df is not None:
        numeric_df = df.select_dtypes(include=[np.number])
        analysis = {
            'mean': numeric_df.mean(),
            'median': numeric_df.median(),
            'std_dev': numeric_df.std()
        }
        analysis_df = pd.DataFrame(analysis)
        print("Analysis performed successfully.")
        return analysis_df
    else:
        print("No data to analyze.")
        return None

# Function to save the analysis results to a new CSV file
def save_to_csv(df, file_path):
    if df is not None:
        try:
            df.to_csv(file_path, index=False)
            print(f"Analysis results saved to {file_path}")
        except Exception as e:
            print(f"Error: Could not save the file at {file_path}. Exception: {e}")

# Main script
if __name__ == "__main__":
    input_file = r"C:\Users\USER\OneDrive\Documents\NewBlackFriday.csv"  # Path to the input CSV file
    output_file = r"C:\Users\USER\OneDrive\Documents\analysis_results.csv"  # Path to the output CSV file

    # Reading data
    data = read_csv(input_file)

    # Performing analysis
    analysis_results = analyze_data(data)

    # Saving results
    save_to_csv(analysis_results, output_file)


File read successfully.
Analysis performed successfully.
Analysis results saved to C:\Users\USER\OneDrive\Documents\analysis_results.csv


In [20]:
import pandas as pd 
import numpy as np 

data = pd.read_csv(r"C:\Users\USER\OneDrive\Documents\analysis_results.csv")
data

mean     median        std_dev
0  2.750335e+05   275033.5  158791.098273
1  1.003029e+06  1003077.0    1727.591586
2  8.076707e+00        7.0       6.522660
3  4.096530e-01        0.0       0.491770
4  5.404270e+00        5.0       3.936211
5  9.863190e+00        9.0       5.049456
6  1.265072e+01       14.0       4.115118
7  9.263969e+03     8047.0    5023.065394

### ARRAY OPERATIONS ( DAY 10) 

In [1]:
# Import numpy library 
import numpy as np

In [3]:
# Create Numpy Arrays 
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Basic arithmetic operations
add_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2
divide_result = array1 / array2


print(add_result)
print(subtract_result)
print(multiply_result)
print(divide_result)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [11]:
# Checking the shape of the array 
array1.shape
array2.shape

(5,)

In [8]:
# Aggregation functions on Array 1
sum_result = np.sum(array1)
mean_result = np.mean(array1)
max_result = np.max(array1)

print(sum_result)
print(mean_result)
print(max_result)

15
3.0
5


In [9]:
# Aggregation functions on Array 2
sum_result = np.sum(array2)
mean_result = np.mean(array2)
max_result = np.max(array2)

print(sum_result)
print(mean_result)
print(max_result)

150
30.0
50


### NUMPY BOOLEAN ARRAY ( DAY 11 )

In [8]:
# Import Numpy library 
import numpy as np

# Create a sample NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a boolean array by applying a condition
bool_arr = arr > 5

print("Boolean array:", bool_arr)

# Use boolean indexing to select elements
selected_elements = arr[bool_arr]
print("Elements greater than 5:", selected_elements)

# Demonstrating boolean operations
condition1 = arr > 3
condition2 = arr < 8

and_result = np.logical_and(condition1, condition2)
print("Elements between 3 and 8 (AND):", arr[and_result])

or_result = np.logical_or(condition1, condition2)
print("Elements greater than 3 OR less than 8 (OR):", arr[or_result])

not_result = np.logical_not(condition1)
print("Elements NOT greater than 3 (NOT):", arr[not_result])

Boolean array: [False False False False False  True  True  True  True  True]
Elements greater than 5: [ 6  7  8  9 10]
Elements between 3 and 8 (AND): [4 5 6 7]
Elements greater than 3 OR less than 8 (OR): [ 1  2  3  4  5  6  7  8  9 10]
Elements NOT greater than 3 (NOT): [1 2 3]


In [9]:
# Import library (Example 2)
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Perform boolean indexing to select elements greater than 5
greater_than_five = arr > 5

# Perform boolean indexing to select even elements
even_elements = arr % 2 == 0
  
# Combine conditions using logical AND: elements greater than 5 AND even
greater_than_five_and_even = np.logical_and(arr > 5, arr % 2 == 0)

# Combine conditions using logical OR: elements less than 3 OR greater than 8
less_than_three_or_greater_than_eight = np.logical_or(arr < 3, arr > 8)

# Use logical NOT: elements NOT greater than 5
not_greater_than_five = np.logical_not(arr > 5)

print("Elements greater than 5:", arr[greater_than_five])
print("Even elements:", arr[even_elements])
print("Elements greater than 5 and even:", arr[greater_than_five_and_even]) 
print("Elements less than 3 or greater than 8:", arr[less_than_three_or_greater_than_eight])
print("Elements not greater than 5:", arr[not_greater_than_five])   

Elements greater than 5: [ 6  7  8  9 10]
Even elements: [ 2  4  6  8 10]
Elements greater than 5 and even: [ 6  8 10]
Elements less than 3 or greater than 8: [ 1  2  9 10]
Elements not greater than 5: [1 2 3 4 5]


### Numpy Algebra and Size (DAY 12)

In [1]:
# Matrix Multiplication using np.dot()

import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = np.dot(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C (A dot B):")
print(C)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix C (A dot B):
[[19 22]
 [43 50]]


In [2]:
# Array Resizing using np.resize()

# Define an array
A = np.array([[1, 2, 3], [4, 5, 6]])

# Resize the array to a new shape (3, 4)
A_resized = np.resize(A, (3, 4))

print("\nOriginal Array A:")
print(A)
print("\nResized Array A_resized (3x4):")
print(A_resized)


Original Array A:
[[1 2 3]
 [4 5 6]]

Resized Array A_resized (3x4):
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


In [3]:
# Array Reshaping using np.reshape()

# Define an array
B = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape the array to a new shape (3, 2)
B_reshaped = B.reshape((3, 2))

print("\nOriginal Array B:")
print(B)
print("\nReshaped Array B_reshaped (3x2):")
print(B_reshaped)


Original Array B:
[[1 2 3]
 [4 5 6]]

Reshaped Array B_reshaped (3x2):
[[1 2]
 [3 4]
 [5 6]]


### PANDA SERIES ( DAY 13) 

In [2]:
# Import pandas library
import pandas as pd

# Creating a Pandas Series from a Python list
data_list = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data_list, index=['a', 'b', 'c', 'd', 'e'])

print("Pandas Series from List:")
print(series_from_list)

# Accessing elements in the Series
print("\nAccessing elements:")
print("Element at index 'a':", series_from_list['a'])
print("Element at index 'c':", series_from_list['c'])

# Slicing the Series
print("\nSlicing the Series:")
print("Slicing from index 'b' to 'd':")
print(series_from_list['b':'d'])

# Basic operations on Series
print("\nBasic operations on Series:")
print("Series after adding 5 to each element:")
print(series_from_list + 5)
print("Series after multiplying each element by 2:")
print(series_from_list * 2)
print("Mean of the Series:", series_from_list.mean())
print("Sum of the Series:", series_from_list.sum())

Pandas Series from List:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Accessing elements:
Element at index 'a': 10
Element at index 'c': 30

Slicing the Series:
Slicing from index 'b' to 'd':
b    20
c    30
d    40
dtype: int64

Basic operations on Series:
Series after adding 5 to each element:
a    15
b    25
c    35
d    45
e    55
dtype: int64
Series after multiplying each element by 2:
a     20
b     40
c     60
d     80
e    100
dtype: int64
Mean of the Series: 30.0
Sum of the Series: 150


### Pandas DataFrames ( DAY 14 )

In [2]:
import pandas as pd

# Creating a data frame from a dictionary
data = {
    'Name': ['Angela', 'Bianca', 'Meredith', 'Derek'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df_dict = pd.DataFrame(data)
print("DataFrame from dictionary:")
print(df_dict)

# Save the DataFrame to a CSV file for demonstration purposes
df_dict.to_csv('example.csv', index=False)

# Creating a DataFrame from a CSV file
df_csv = pd.read_csv('example.csv')
print("\nDataFrame from CSV file:")
print(df_csv)

# Selecting columns
selected_columns = df_csv[['Name', 'City']]
print("\nSelected columns (Name and City):")
print(selected_columns)

# Filtering rows where Age is greater than 25
filtered_rows = df_csv[df_csv['Age'] > 25]
print("\nFiltered rows where Age > 25:")
print(filtered_rows)

# Adding a new column 'AgeGroup'
df_csv['AgeGroup'] = df_csv['Age'].apply(lambda x: 'Young' if x < 30 else 'Mature')
print("\nDataFrame with new column 'AgeGroup':")
print(df_csv)

DataFrame from dictionary:
       Name  Age         City
0    Angela   24     New York
1    Bianca   27  Los Angeles
2  Meredith   22      Chicago
3     Derek   32      Houston

DataFrame from CSV file:
       Name  Age         City
0    Angela   24     New York
1    Bianca   27  Los Angeles
2  Meredith   22      Chicago
3     Derek   32      Houston

Selected columns (Name and City):
       Name         City
0    Angela     New York
1    Bianca  Los Angeles
2  Meredith      Chicago
3     Derek      Houston

Filtered rows where Age > 25:
     Name  Age         City
1  Bianca   27  Los Angeles
3   Derek   32      Houston

DataFrame with new column 'AgeGroup':
       Name  Age         City AgeGroup
0    Angela   24     New York    Young
1    Bianca   27  Los Angeles    Young
2  Meredith   22      Chicago    Young
3     Derek   32      Houston   Mature


### INDEXING AND CONDITIONALS ( DAY 15 )

In [2]:
import pandas as pd

# Sample data
data = {
    'Name': ['Angela', 'Bianca', 'Meredith', 'Derek'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Score': [85, 90, 88, 92]
}

# Create DataFrame
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Using .loc[] to select rows and columns by label
print("\nUsing .loc[] to select specific rows and columns by label:")

# Select rows with index 1 and 2, and columns 'Name' and 'City'
print(df.loc[1:2, ['Name', 'City']])

# Using .iloc[] to select rows and columns by position
print("\nUsing .iloc[] to select specific rows and columns by position:")
# Select first 3 rows and first 2 columns
print(df.iloc[0:3, 0:2])

Original DataFrame:
       Name  Age         City  Score
0    Angela   24     New York     85
1    Bianca   27  Los Angeles     90
2  Meredith   22      Chicago     88
3     Derek   32      Houston     92

Using .loc[] to select specific rows and columns by label:
       Name         City
1    Bianca  Los Angeles
2  Meredith      Chicago

Using .iloc[] to select specific rows and columns by position:
       Name  Age
0    Angela   24
1    Bianca   27
2  Meredith   22


In [3]:
# Conditional operations to filter rows based on specific criteria
print("\nFiltering rows where Age is greater than 25:")
age_filter = df['Age'] > 25
print(df.loc[age_filter])

print("\nFiltering rows where City is 'Chicago' or 'Houston':")
city_filter = df['City'].isin(['Chicago', 'Houston'])
print(df.loc[city_filter])

print("\nFiltering rows where Score is above 85 and Age is less than 30:")
score_age_filter = (df['Score'] > 85) & (df['Age'] < 30)
print(df.loc[score_age_filter])


Filtering rows where Age is greater than 25:
     Name  Age         City  Score
1  Bianca   27  Los Angeles     90
3   Derek   32      Houston     92

Filtering rows where City is 'Chicago' or 'Houston':
       Name  Age     City  Score
2  Meredith   22  Chicago     88
3     Derek   32  Houston     92

Filtering rows where Score is above 85 and Age is less than 30:
       Name  Age         City  Score
1    Bianca   27  Los Angeles     90
2  Meredith   22      Chicago     88
